mkdir modelweights
cd modelweights

wget https://huggingface.co/bigscience/bloomz/resolve/main/config.json
wget https://huggingface.co/bigscience/bloomz/resolve/main/tokenizer.json
wget https://huggingface.co/bigscience/bloomz/resolve/main/tokenizer.json
wget https://huggingface.co/bigscience/bloomz/resolve/main/tokenizer_config.json
wget https://huggingface.co/bigscience/bloomz/resolve/main//config.json
wget https://huggingface.co/bigscience/bloomz/resolve/main//pytorch_model.bin.index.json
wget https://huggingface.co/bigscience/bloomz/resolve/main//special_tokens_map.json
wget https://huggingface.co/bigscience/bloomz/resolve/main//tokenizer.json
wget https://huggingface.co/bigscience/bloomz/resolve/main//tokenizer_config.json
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00001-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00002-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00003-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00004-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00005-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00006-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00007-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00008-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00009-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00010-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00011-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00012-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00013-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00014-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00015-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00016-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00017-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00018-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00019-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00020-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00021-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00022-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00023-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00024-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00025-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00026-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00027-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00028-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00029-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00030-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00031-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00032-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00033-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00034-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00035-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00036-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00037-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00038-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00039-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00040-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00041-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00042-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00043-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00044-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00045-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00046-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00047-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00048-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00049-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00050-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00051-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00052-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00053-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00054-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00055-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00056-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00057-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00058-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00059-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00060-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00061-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00062-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00063-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00064-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00065-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00066-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00067-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00068-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00069-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00070-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00071-of-00072.bin
wget https://huggingface.co/bigscience/bloomz/resolve/main/pytorch_model_00072-of-00072.bin
